from pathlib import Path
import re
base=Path('/mnt/data/emotion_island_v13')
small=base/'emotion_my_world.html'; main=base/'emotion_island.html'; score=base/'emotion_score.html'
POST='''\n<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/postprocessing/Pass.js"></script>\n<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/shaders/CopyShader.js"></script>\n<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/shaders/LuminosityHighPassShader.js"></script>\n<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/postprocessing/ShaderPass.js"></script>\n<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/postprocessing/EffectComposer.js"></script>\n<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/postprocessing/RenderPass.js"></script>\n<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/postprocessing/UnrealBloomPass.js"></script>'''

def bump(t):
    t=t.replace('v1.2','v1.3').replace('V12','V13')
    t=t.replace('emotionIslandV12:', 'emotionIslandV13:').replace('emotionIslandV12','emotionIslandV13')
    return t

# ---------- SMALL WORLD ----------
s=bump(small.read_text())
loader='<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/loaders/GLTFLoader.js"></script>'
s=s.replace(loader, loader+POST)
s=s.replace('<div class="badge">v1.3 GAME ART · 拖曳旋轉 · 滾輪/雙指縮放</div>', '<div class="badge">v1.3 CINEMATIC · 拖曳旋轉 · 滾輪/雙指縮放</div><button class="action cinematic-toggle" id="fxToggle" title="切換電影光效">✨ 電影光效</button>')
old='const AssetBank=window.EmotionAssetBank||null;let assetsRebuilt=false,attractionPoints=[];'
new=r'''const AssetBank=window.EmotionAssetBank||null;let assetsRebuilt=false,attractionPoints=[],themeFx=null;
const BLOOM_LAYER=1;let bloomComposer=null,finalComposer=null,bloomPass=null,cinematicAvailable=false;let cinematicEnabled=localStorage.getItem('emotionIslandFx')!=='off';
function markGlow(o){if(!o)return o;o.traverse&&o.traverse(x=>{if(x.layers)x.layers.enable(BLOOM_LAYER)});if(o.layers)o.layers.enable(BLOOM_LAYER);return o}
function initCinematic(){try{if(!(THREE.EffectComposer&&THREE.RenderPass&&THREE.UnrealBloomPass&&THREE.ShaderPass))return false;const mobile=matchMedia('(max-width:800px)').matches,res=new THREE.Vector2(Math.max(2,innerWidth*(mobile?.58:.72)),Math.max(2,innerHeight*(mobile?.58:.72)));bloomComposer=new THREE.EffectComposer(renderer);bloomComposer.renderToScreen=false;bloomComposer.addPass(new THREE.RenderPass(scene,camera));bloomPass=new THREE.UnrealBloomPass(res,mobile?.42:.64,.68,.20);bloomComposer.addPass(bloomPass);finalComposer=new THREE.EffectComposer(renderer);finalComposer.addPass(new THREE.RenderPass(scene,camera));const finalPass=new THREE.ShaderPass(new THREE.ShaderMaterial({uniforms:{baseTexture:{value:null},bloomTexture:{value:bloomComposer.renderTarget2.texture}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D baseTexture;uniform sampler2D bloomTexture;varying vec2 vUv;void main(){vec4 b=texture2D(baseTexture,vUv);vec4 g=texture2D(bloomTexture,vUv);gl_FragColor=b+g*.82;}'}),'baseTexture');finalPass.needsSwap=true;finalComposer.addPass(finalPass);cinematicAvailable=true;return true}catch(e){console.warn('[emotion-island] cinematic fallback',e);bloomComposer=finalComposer=null;return false}}
function renderSceneCinematic(){if(cinematicEnabled&&cinematicAvailable&&bloomComposer&&finalComposer){const mask=camera.layers.mask;camera.layers.set(BLOOM_LAYER);bloomComposer.render();camera.layers.mask=mask;finalComposer.render()}else renderer.render(scene,camera)}
function syncFxButton(){const b=document.getElementById('fxToggle');if(!b)return;b.textContent=cinematicAvailable?(cinematicEnabled?'✨ 電影光效':'◇ 流暢模式'):'◇ 基本光效';b.classList.toggle('fx-off',!cinematicEnabled||!cinematicAvailable)}
function contactShadow(radius=.8,opacity=.14){const s=new THREE.Mesh(new THREE.CircleGeometry(1,28),new THREE.MeshBasicMaterial({color:0x071326,transparent:true,opacity,depthWrite:false}));s.rotation.x=-Math.PI/2;s.position.y=.018;s.scale.set(radius,radius*.72,1);s.userData.contactShadow=true;return s}
function createThemeAtmosphere(id,th){const g=new THREE.Group(),count=(id==='1'||id==='5'||id==='8')?190:120,geo=new THREE.BufferGeometry(),arr=new Float32Array(count*3);for(let i=0;i<count;i++){const a=i*2.399963+Number(id),r=4.5+(i%31)/30*11.5;arr[i*3]=Math.cos(a)*r;arr[i*3+1]=2+((i*17)%100)/100*10;arr[i*3+2]=Math.sin(a)*r*.80}geo.setAttribute('position',new THREE.BufferAttribute(arr,3));const colors={1:0xb8e9ff,2:0xffb7d7,3:0x9df0af,4:0xffd48a,5:0xbcc9ff,6:0xffb8df,7:0x8cffff,8:0xcabaff};const pts=new THREE.Points(geo,new THREE.PointsMaterial({color:colors[id]||th.accent,size:id==='3'?.10:.075,transparent:true,opacity:(id==='1'||id==='5')?.70:.48,depthWrite:false,blending:THREE.AdditiveBlending}));pts.userData.fxPoints=true;g.add(markGlow(pts));if(id==='8'){for(let i=0;i<3;i++){const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,uniforms:{uTime:{value:0},c1:{value:new THREE.Color(i===1?0x65ffd1:0x7fa7ff)},c2:{value:new THREE.Color(i===2?0xf6a9ff:0xb292ff)}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform float uTime;uniform vec3 c1;uniform vec3 c2;varying vec2 vUv;void main(){float wave=.5+.5*sin(vUv.x*7.0+uTime*.75+vUv.y*3.0);float edge=smoothstep(0.0,.18,vUv.x)*smoothstep(1.0,.82,vUv.x);float fade=smoothstep(0.0,.18,vUv.y)*(1.0-smoothstep(.72,1.0,vUv.y));float a=edge*fade*(.10+.18*wave);gl_FragColor=vec4(mix(c1,c2,vUv.y+wave*.12),a);}'});const p=new THREE.Mesh(new THREE.PlaneGeometry(10,22,18,18),mat);p.position.set((i-1)*8,12,-29-i*2);p.rotation.y=(i-1)*.12;g.add(markGlow(p))}}if(id==='1'||id==='8'){const lineMat=new THREE.LineBasicMaterial({color:id==='1'?0xbcecff:0xe5c6ff,transparent:true,opacity:.78,blending:THREE.AdditiveBlending}),meteor=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(-4.5,.65,0)]),lineMat);meteor.position.set(16,19,-31);meteor.userData.meteor=true;g.add(markGlow(meteor))}g.userData.themeId=id;return g}
function updateThemeAtmosphere(t){if(!themeFx)return;themeFx.rotation.y=Math.sin(t*.000055)*.025;themeFx.children.forEach((o,i)=>{if(o.userData.fxPoints){o.rotation.y=t*.000018;o.position.y=Math.sin(t*.00032+i)*.10}if(o.material&&o.material.uniforms&&o.material.uniforms.uTime)o.material.uniforms.uTime.value=t*.001;if(o.userData.meteor){const u=(t*.000045)%1;o.position.x=19-u*38;o.position.y=18+u*6;o.material.opacity=u>.96?(1-u)/.04:.72}})}'''
if old not in s: raise SystemExit('small insertion missing')
s=s.replace(old,new)
s=s.replace("function gameAsset(name){if(!AssetBank||!AssetBank.ready)return null;const o=AssetBank.clone(name);if(!o)return null;o.traverse(x=>{if(x.isMesh){x.castShadow=true;x.receiveShadow=true}});return o}","function gameAsset(name){if(!AssetBank||!AssetBank.ready)return null;const o=AssetBank.clone(name);if(!o)return null;o.traverse(x=>{if(x.isMesh){x.castShadow=true;x.receiveShadow=true;if(x.material&&['crystal','lantern','campfire'].includes(name)){const ms=Array.isArray(x.material)?x.material:[x.material];ms.forEach(m=>{if('emissive' in m){m.emissive=new THREE.Color(name==='campfire'?0xff6d2d:(name==='lantern'?0xffc36a:0x3fd8ff));m.emissiveIntensity=name==='campfire'?1.1:.65}})}}});if(['crystal','lantern','campfire'].includes(name))markGlow(o);return o}")
s=s.replace("return new THREE.Mesh(new THREE.TubeGeometry(curve,144,tube,6,true),new THREE.MeshBasicMaterial({color,transparent:true,opacity,blending:THREE.AdditiveBlending,depthWrite:false}))}","return markGlow(new THREE.Mesh(new THREE.TubeGeometry(curve,144,tube,6,true),new THREE.MeshBasicMaterial({color,transparent:true,opacity,blending:THREE.AdditiveBlending,depthWrite:false})))}")
s=s.replace("if(amap[id]){const aa=gameAsset(amap[id]);if(aa)return aa}","if(amap[id]){const aa=gameAsset(amap[id]);if(aa){if(['lantern','crystal','campfire'].includes(id))markGlow(aa);return aa}}")
s=s.replace("else if(id==='gazebo'){for(let i=0;i<6;i++){const a=i/6*Math.PI*2,p=new THREE.Mesh(new THREE.CylinderGeometry(.045,.06,1.4,6),toon(0xf0d3c8));p.position.set(Math.cos(a)*.72,.7,Math.sin(a)*.72);g.add(p)}const roof=new THREE.Mesh(new THREE.ConeGeometry(1.05,.60,6),toon(0xd98fb2));roof.position.y=1.55;g.add(roof)}return g}","else if(id==='gazebo'){for(let i=0;i<6;i++){const a=i/6*Math.PI*2,p=new THREE.Mesh(new THREE.CylinderGeometry(.045,.06,1.4,6),toon(0xf0d3c8));p.position.set(Math.cos(a)*.72,.7,Math.sin(a)*.72);g.add(p)}const roof=new THREE.Mesh(new THREE.ConeGeometry(1.05,.60,6),toon(0xd98fb2));roof.position.y=1.55;g.add(roof)}if(['lantern','crystal','campfire'].includes(id))markGlow(g);return g}")
s=s.replace("g.add(glow);const ring=", "g.add(markGlow(glow));const ring=").replace("ring.rotation.z=.22;g.add(ring);", "ring.rotation.z=.22;g.add(markGlow(ring));")
s=s.replace("g.userData.centerpiece=true;\n  return g;", "g.userData.centerpiece=true;markGlow(g);\n  return g;")
s=s.replace("if(th.special==='stars'||th.special==='moon'||th.special==='hope'){for(let i=0;i<28;i++){const st=new THREE.Mesh(new THREE.OctahedronGeometry(.045+(i%4)*.012),new THREE.MeshBasicMaterial({color:i%3?0xdce8ff:th.accent,transparent:true,opacity:.78}));st.position.set(-32+(i*17%64),8+(i*11%18),-35-(i%7)*4);root.add(st)}}", "if(th.special==='stars'||th.special==='moon'||th.special==='hope'){for(let i=0;i<28;i++){const st=new THREE.Mesh(new THREE.OctahedronGeometry(.045+(i%4)*.012),new THREE.MeshBasicMaterial({color:i%3?0xdce8ff:th.accent,transparent:true,opacity:.78}));st.position.set(-32+(i*17%64),8+(i*11%18),-35-(i%7)*4);root.add(st)}}themeFx=createThemeAtmosphere(id,th);root.add(themeFx);")
oldrp="o.rotation.y=Number(p.rot)||0;o.scale.setScalar(itemScale(p.itemId));o.userData.slot=Number(slot);placedGroup.add(o);if(interest[p.itemId])"
if oldrp not in s: raise SystemExit('renderPlaced missing')
s=s.replace(oldrp,"o.rotation.y=Number(p.rot)||0;o.scale.setScalar(itemScale(p.itemId));o.userData.slot=Number(slot);o.add(contactShadow(itemFootprint(p.itemId)*1.08/itemScale(p.itemId),p.itemId==='flowerPatch'?.07:.13));placedGroup.add(o);if(interest[p.itemId])")
pat=r"function updateSpirits\(t\)\{.*?\}\nfunction renderEditor"
m=re.search(pat,s,re.S)
if not m: raise SystemExit('updateSpirits missing')
fun=r'''function updateSpirits(t){if(!peopleGroup)return;const cycle=17000;peopleGroup.children.forEach((sp,i)=>{const ud=sp.userData,pair=ud.chatPair;let chatting=false,usingProp=false,kind='';if(pair>=0&&pair<4){const local=(t+pair*2100)%cycle,spot=chatSpots[pair],side=i%2===0?-1:1;if(local>5200&&local<13200){setSpiritTarget(sp,spot[0]+side*.62,spot[1]+side*.10);chatting=local>8200&&local<12800}}if(!chatting&&ud.activityUntil&&t<ud.activityUntil&&ud.activityPoint){const ap=ud.activityPoint,side=i%2?1:-1;kind=ap.kind||'';let spread=ap.r*.38+.18;if(kind==='campfire'||kind==='fountain')spread=ap.r*.72+.32;if(kind==='telescope')spread=.28;setSpiritTarget(sp,ap.x+side*spread,ap.z+.18*side);usingProp=Math.hypot(sp.position.x-ud.dest.x,sp.position.z-ud.dest.z)<.32}else if(!chatting&&t>ud.nextDecision&&!(pair>=0&&((t+pair*2100)%cycle)>5200&&((t+pair*2100)%cycle)<13200)){const chooseProp=attractionPoints.length&&((i+Math.floor(t/3900))%3!==0);if(chooseProp){const ap=attractionPoints[(i*5+Math.floor(t/6500))%attractionPoints.length];ud.activityPoint=ap;ud.activityUntil=t+5200+((i*773)%2800);ud.nextDecision=ud.activityUntil+900;const side=i%2?1:-1;setSpiritTarget(sp,ap.x+side*(ap.r*.38+.18),ap.z+.18*side)}else{ud.activityPoint=null;ud.activityUntil=0;ud.nextDecision=t+3500+((i*971)%3900);const ang=(Math.sin(t*.00031+ud.seed)*.5+.5)*Math.PI*2,r=4+((i*37)%100)/100*5.2;setSpiritTarget(sp,Math.cos(ang)*r,Math.sin(ang)*r*.78)}}const dx=ud.dest.x-sp.position.x,dz=ud.dest.z-sp.position.z,d=Math.hypot(dx,dz),walking=d>.12;if(walking){const step=Math.min(d,ud.speed);sp.position.x+=dx/d*step;sp.position.z+=dz/d*step;sp.rotation.y=Math.atan2(dx,dz)}const sitting=usingProp&&['bench','picnic','gazebo'].includes(kind),swinging=usingProp&&kind==='swing',stargazing=usingProp&&kind==='telescope';const bs=ud.baseScale||.40,targetSy=sitting?bs*.78:bs;sp.scale.x+=(bs-sp.scale.x)*.12;sp.scale.y+=(targetSy-sp.scale.y)*.12;sp.scale.z+=(bs-sp.scale.z)*.12;let y=1.62+(walking?Math.abs(Math.sin(t*.010+i))*.055:Math.sin(t*.002+i)*.020);if(sitting)y-=.08;if(swinging)y+=.08+Math.sin(t*.007+i)*.11;sp.position.y=y;if(stargazing&&!walking){sp.rotation.x=-.13;sp.rotation.y=Math.atan2(sp.position.x,sp.position.z)+Math.PI}else sp.rotation.x*=.84;if(ud.armL&&ud.armR){let sw=walking?Math.sin(t*.012+i)*.45:0;if(usingProp&&kind==='campfire')sw=Math.sin(t*.006+i)*.18;if(stargazing)sw=.35;ud.armL.rotation.x=sw;ud.armR.rotation.x=-sw}if(ud.bubble)ud.bubble.visible=chatting||usingProp;if(ud.label)ud.label.visible=orbitDistance<13.5||chatting||usingProp})}
function renderEditor'''
s=s[:m.start()]+fun+s[m.end():]
s=s.replace("sp.scale.setScalar(.40);sp.userData.home", "sp.scale.setScalar(.40);sp.userData.baseScale=.40;sp.userData.home")
s=s.replace("if(AssetBank&&THREE.GLTFLoader){AssetBank.load('assets/models/').then(ok=>{if(ok&&gid&&!assetsRebuilt){assetsRebuilt=true;buildWorld(gid)}})}", "initCinematic();syncFxButton();const fxButton=document.getElementById('fxToggle');if(fxButton)fxButton.onclick=()=>{cinematicEnabled=!cinematicEnabled;localStorage.setItem('emotionIslandFx',cinematicEnabled?'on':'off');syncFxButton()};if(AssetBank&&THREE.GLTFLoader){AssetBank.load('assets/models/').then(ok=>{if(ok&&gid&&!assetsRebuilt){assetsRebuilt=true;buildWorld(gid)}})}")
s=s.replace("if(motes)motes.rotation.y=t*.000028;if(previewObject", "if(motes)motes.rotation.y=t*.000028;updateThemeAtmosphere(t);if(previewObject")
s=s.replace("previewRenderer.render(previewScene,previewCamera)}renderer.render(scene,camera)}animate(0);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});", "previewRenderer.render(previewScene,previewCamera)}renderSceneCinematic()}animate(0);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(bloomComposer)bloomComposer.setSize(innerWidth,innerHeight);if(finalComposer)finalComposer.setSize(innerWidth,innerHeight)});")
s=s.replace('</body></html>', '''<style id="v13-cinematic-css">.cinematic-toggle{background:linear-gradient(90deg,rgba(119,226,255,.18),rgba(184,142,255,.22))!important}.cinematic-toggle.fx-off{opacity:.64;background:rgba(255,255,255,.06)!important}@media(max-width:800px){.cinematic-toggle{padding:9px 10px!important;font-size:9px!important}}</style></body></html>''')
small.write_text(s)

# ---------- MAIN WORLD ----------
s=bump(main.read_text())
three='<script src="https://cdn.jsdelivr.net/npm/three@0.128.0/build/three.min.js" onerror="this.onerror=null;this.src=\'https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js\'"></script>'
s=s.replace(three,three+POST)
s=s.replace('<div class="pill" id="mode">展示模式</div>', '<div class="pill" id="mode">v1.3 CINEMATIC</div><button class="btn cinematic-toggle" id="fxToggleMain">✨ 電影光效</button>')
marker="const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x5967a8,.0042);const camera=new THREE.PerspectiveCamera(39,innerWidth/innerHeight,.1,220);camera.position.set(0,31,48);const look=new THREE.Vector3(0,2,0);"
insert=r'''const BLOOM_LAYER=1;let bloomComposer=null,finalComposer=null,bloomPass=null,cinematicAvailable=false;let cinematicEnabled=localStorage.getItem('emotionIslandFx')!=='off';
function markGlow(o){if(!o)return o;o.traverse&&o.traverse(x=>{if(x.layers)x.layers.enable(BLOOM_LAYER)});if(o.layers)o.layers.enable(BLOOM_LAYER);return o}
function initCinematic(){try{if(!(THREE.EffectComposer&&THREE.RenderPass&&THREE.UnrealBloomPass&&THREE.ShaderPass))return false;const res=new THREE.Vector2(innerWidth*.66,innerHeight*.66);bloomComposer=new THREE.EffectComposer(renderer);bloomComposer.renderToScreen=false;bloomComposer.addPass(new THREE.RenderPass(scene,camera));bloomPass=new THREE.UnrealBloomPass(res,.50,.72,.18);bloomComposer.addPass(bloomPass);finalComposer=new THREE.EffectComposer(renderer);finalComposer.addPass(new THREE.RenderPass(scene,camera));const finalPass=new THREE.ShaderPass(new THREE.ShaderMaterial({uniforms:{baseTexture:{value:null},bloomTexture:{value:bloomComposer.renderTarget2.texture}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D baseTexture;uniform sampler2D bloomTexture;varying vec2 vUv;void main(){gl_FragColor=texture2D(baseTexture,vUv)+texture2D(bloomTexture,vUv)*.72;}'}),'baseTexture');finalPass.needsSwap=true;finalComposer.addPass(finalPass);cinematicAvailable=true;return true}catch(e){console.warn('[emotion-island] main cinematic fallback',e);return false}}
function renderSceneCinematic(){if(cinematicEnabled&&cinematicAvailable&&bloomComposer&&finalComposer){const mask=camera.layers.mask;camera.layers.set(BLOOM_LAYER);bloomComposer.render();camera.layers.mask=mask;finalComposer.render()}else renderer.render(scene,camera)}
function syncFxButton(){const b=document.getElementById('fxToggleMain');if(!b)return;b.textContent=cinematicAvailable?(cinematicEnabled?'✨ 電影光效':'◇ 流暢模式'):'◇ 基本光效';b.classList.toggle('fx-off',!cinematicEnabled||!cinematicAvailable)}'''
if marker not in s: raise SystemExit('main marker missing')
s=s.replace(marker,marker+insert)
s=s.replace("g.add(rim);const deco", "g.add(markGlow(rim));const deco")
s=s.replace("hub.add(crown);", "hub.add(markGlow(crown));").replace("hub.add(fall)}", "hub.add(markGlow(fall))}").replace("scene.add(pulse);links.push", "scene.add(markGlow(pulse));links.push")
# init before interaction listeners: insert before animate definition
s=s.replace("function animate(t){requestAnimationFrame(animate);", "initCinematic();syncFxButton();const fxMain=document.getElementById('fxToggleMain');if(fxMain)fxMain.onclick=()=>{cinematicEnabled=!cinematicEnabled;localStorage.setItem('emotionIslandFx',cinematicEnabled?'on':'off');syncFxButton()};\nfunction animate(t){requestAnimationFrame(animate);")
s=s.replace("crown.rotation.z=t*.00011;renderer.render(scene,camera)}animate(0);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});", "crown.rotation.z=t*.00011;renderSceneCinematic()}animate(0);addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);if(bloomComposer)bloomComposer.setSize(innerWidth,innerHeight);if(finalComposer)finalComposer.setSize(innerWidth,innerHeight)});")
s=s.replace('</body></html>', '''<style id="v13-cinematic-css">.cinematic-toggle{background:linear-gradient(90deg,rgba(119,226,255,.18),rgba(184,142,255,.22))!important}.cinematic-toggle.fx-off{opacity:.64;background:rgba(17,22,54,.56)!important}@media(max-width:720px){.cinematic-toggle{font-size:9px;padding:10px!important}}</style></body></html>''')
main.write_text(s)

# ---------- SCORE ----------
score.write_text(bump(score.read_text()))
