import {LIFE_STAGES,lifeFor,npcDialogue,npcRequest} from './life.js';
import {sessionConfig,pageHref,visitScope,islandHref} from './session.js';
import {CloudIslandStore,watchRoom,stateFromRoot} from './cloud.js';
import { installNavigation } from './navigation.js';
import { parsePreviewRoom,IslandStore,LayoutHistory,CATALOG,CATEGORIES,NPCS,QUESTS,clone,THEMES,growthFor,availableNpcs,memberAppearance,leaderState,validateState,totalScore } from './state.js';
import { IslandWorld,Thumbnails,ModelPreview } from './world.js';
import { ZONES } from './terrain.js';
import { icon,hydrateIcons } from './icons.js';

const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
hydrateIcons();
let config,store,world,thumbs,history;
let collection='inventory',category='全部',mode='walk',activeNpc=null,placing=null,modelPreview=null,toastTimer=0,audioContext=null,lastPanelFocus=null,thumbObserver=null,thumbGeneration=0;
const panel=$('panel-dialog'),dialogueTurns=new Map();let ambientTimer=0;
function visitorHref(group){return islandHref(config,group);}
try{
  config=sessionConfig(location.search,location.hostname);
  if(location.pathname.includes('leader_world'))Object.assign(config,{leader:true,viewer:true});if(location.pathname.includes('gallery'))Object.assign(config,{gallery:true,viewer:true});
  config=visitScope(config,sessionStorage,location.search,!config.leader);
  store=config.leader?{state:leaderState(),layout(){return clone({inventory:this.state.inventory,placements:this.state.placements});}}:(config.cloud?new CloudIslandStore(config.room,config.group,config.viewer):new IslandStore(localStorage,config.group,config.viewer));if(config.cloud&&!config.leader)await store.load();history=new LayoutHistory(store.layout());
  world=new IslandWorld($('scene'),store.state);thumbs=new Thumbnails();
  wire();refresh();if(config.cloud&&!config.leader)watchRoom(config.room,receiveCloud,e=>toast(e.message,true),{interval:config.viewer?12000:4000});world.focus(config.leader?{x:0,z:0,y:7,zoom:.62,name:'星宮前庭'}:{x:-2,z:5,zoom:.98,name:THEMES[config.group-1].title});document.body.classList.toggle('viewer',config.viewer);document.body.classList.toggle('leader-scene',config.leader);if((location.pathname.includes('emotion_score')||new URLSearchParams(location.search).get('panel')==='score')&&!config.viewer)openGrowth();setTimeout(()=>$('world-hint').classList.add('quiet'),11000);
  requestAnimationFrame(()=>requestAnimationFrame(()=>{$('loading').classList.add('leaving');setTimeout(()=>$('loading').hidden=true,650);window.islandReady=true;}));
}catch(error){$('boot-error').hidden=false;$('boot-error-message').textContent=error.message;$('loading').hidden=true;console.error(error);}

function toast(message,error=false){clearTimeout(toastTimer);$('toast-region').innerHTML=`<div class="toast${error?' error':''}">${esc(message)}</div>`;toastTimer=setTimeout(()=>$('toast-region').replaceChildren(),4200);}
async function run(fn){try{return await fn();}catch(e){console.error(e);toast(e.message,true);return false;}}
function receiveCloud(root){
  if(store.pending)return;const next=stateFromRoot(root,config.room,config.group);if(next.revision<store.state.revision||next.score<store.state.score)return;if(JSON.stringify(next)===JSON.stringify(store.state))return;
  const changed=JSON.stringify(store.layout())!==JSON.stringify({inventory:next.inventory,placements:next.placements});
  if((dirty()||placing)&&changed){toast('其他人已儲存新的佈置。你的草稿仍保留，請先匯出再重新整理。',true);return;}
  const draft=dirty()||!!placing;store.state=next;if(!draft)history.rebase(store.layout());world.updateProgress(store.state);if(!draft)world.renderPlacements(store.state.placements);world.setTime(store.state.time);refresh();
}

function editable(){if(config.viewer){toast('目前是參觀模式。');return false;}return true;}
function dirty(){return JSON.stringify(history.present)!==JSON.stringify(store.layout());}
function chirp(kind='tap'){
  if(!$('sound-button').classList.contains('playing'))return;
  try{audioContext ||= new AudioContext();if(audioContext.state==='suspended')audioContext.resume();const t=audioContext.currentTime;[0,.08].forEach((delay,i)=>{const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.type='sine';osc.frequency.value=(kind==='success'?660:520)*(i?1.25:1);gain.gain.setValueAtTime(0,t+delay);gain.gain.linearRampToValueAtTime(.07,t+delay+.008);gain.gain.exponentialRampToValueAtTime(.001,t+delay+.16);osc.connect(gain);gain.connect(audioContext.destination);osc.start(t+delay);osc.stop(t+delay+.18);});}catch{ /* Sound is optional. */ }
}
function refresh(){
  const tag=document.querySelector('.preview-tag');if(tag)tag.textContent=(config.cloud?'活動房號 · ':'本機預覽 · ')+config.room;const s=store.state;$('wallet-count').textContent=s.spendablePoints.toLocaleString();$('island-name').textContent=s.worldName;$('group-label').textContent=config.leader?'主領班的展示世界':`第${['一','二','三','四','五','六','七','八'][config.group-1]}組${config.viewer?' · 唯讀參觀':'的小世界'}`;document.title=`${s.worldName} — 情緒不孤島 · ${config.room}${config.cloud?'':' 本機預覽'}`;$('location-label').textContent=config.leader?'星宮與月鏡之間':THEMES[config.group-1].title;$('game').setAttribute('aria-label',s.worldName+'互動世界');$('gallery-switcher').hidden=!config.viewer;$('choose-island').textContent=config.leader?'主領班 · 星願神境':s.worldName+' · 唯讀';$('previous-island').href=visitorHref(config.leader?8:(config.group+6)%8+1);$('next-island').href=visitorHref(config.leader?1:config.group%8+1);
  const count=world.members.length;$('avatar-name').textContent=`${count} 位小精靈`;$('avatar-thumb').src=thumbs.avatar(memberAppearance(s,1));$('avatar-thumb').alt='團隊小精靈';$('world-hint').querySelector('span:last-child').textContent=config.leader?'守護每一個心願，也享受自己的日常。':'拖曳看小島 · 點居民聊聊天 · 精靈會自己生活';
  const isDirty=dirty();$('save-button').disabled=!isDirty||!!placing;$('save-button').classList.toggle('dirty',isDirty);$('save-button').setAttribute('aria-label',isDirty?'儲存佈置':'佈置已儲存');$('save-button').title=isDirty?'儲存佈置':'佈置已儲存';$('save-button').innerHTML=icon(isDirty?'download':'check')+`<span>${isDirty?'儲存佈置':'已儲存'}</span>`;
  $('undo-button').disabled=!history.past.length||!!placing;$('redo-button').disabled=!history.future.length||!!placing;
  $('inventory-count').textContent=Object.values(history.present.inventory).reduce((sum,n)=>sum+n,0);
  const done=QUESTS.filter(q=>s.quests[q.id]),todo=QUESTS.filter(q=>!s.quests[q.id]&&(q.unlock||0)<=s.progressScore);const show=todo.length?todo.slice(0,2):done.slice(-2);
  $('quest-peek').innerHTML=show.map(q=>`<div class="peek-row ${s.quests[q.id]?'done':''}"><i>${s.quests[q.id]?'✓':''}</i><span>${q.title}</span></div>`).join('');$('journal-dot').hidden=todo.length===0;$('day-count').textContent=todo.length?String(todo.length):'✓';
  $('time-label').textContent={day:'晴日',sunset:'夕照',night:'星夜'}[s.time];$('time-button').querySelector('span').innerHTML=icon(s.time==='night'?'moon':'sun');
  if(config.viewer){for(const id of ['wallet-button','save-button','avatar-button','day-card'])$(id).hidden=true;document.querySelector('[data-mode="decorate"]').hidden=true;$('island-name').disabled=true;$('journal-button').hidden=true;}
  if(mode==='decorate')renderTray();
}
function wire(){
  document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
  $('save-button').onclick=()=>saveLayout();$('undo-button').onclick=()=>{if(!editable())return;if(history.undo()){world.renderPlacements(history.present.placements);refresh();toast('已復原上一步佈置。');}};
  $('redo-button').onclick=()=>{if(!editable())return;if(history.redo()){world.renderPlacements(history.present.placements);refresh();toast('已重做佈置。');}};
  $('close-tray').onclick=()=>setMode('walk');document.querySelectorAll('[data-collection]').forEach(b=>b.onclick=()=>{collection=b.dataset.collection;category='全部';renderTray();});
  $('rotate-item').onclick=()=>{world.rotateGhost();chirp();};$('cancel-item').onclick=()=>cancelPlacement();$('confirm-item').onclick=()=>confirmPlacement();
  $('snap-button').onclick=()=>{world.snap=!world.snap;$('snap-button').setAttribute('aria-pressed',String(world.snap));const p=world.ghostState();if(p)world.moveGhost(p.x,p.z);};
  $('close-panel').onclick=closePanel;panel.addEventListener('close',()=>{if(modelPreview){modelPreview.dispose();modelPreview=null;}lastPanelFocus?.focus({preventScroll:true});});
  panel.addEventListener('click',e=>{if(e.target===panel){const r=panel.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closePanel();}});
  $('residents-button').onclick=openResidents;$('journal-button').onclick=openJournal;$('journal-mini').onclick=openJournal;$('map-button').onclick=openMap;$('mini-map-button').onclick=openIslands;$('choose-island').onclick=openIslands;
  $('day-toggle').onclick=()=>{const on=$('day-toggle').getAttribute('aria-expanded')!=='true';$('day-toggle').setAttribute('aria-expanded',String(on));$('day-card-details').hidden=!on;$('day-card').classList.toggle('collapsed',!on);$('day-toggle').lastElementChild.innerHTML=icon(on?'minus':'plus');};
  $('avatar-button').onclick=openTeam;$('island-name').onclick=renameIsland;$('wallet-button').onclick=openGrowth;
  $('photo-button').onclick=takePhoto;$('sound-button').onclick=toggleMusic;
  $('time-button').onclick=()=>run(async()=>{const times=['day','sunset','night'],next=times[(times.indexOf(store.state.time)+1)%3];if(!config.viewer)await store.update({time:next});else store.state.time=next;world.setTime(next);refresh();chirp();});
  $('zoom-in').onclick=()=>world.zoom(1.22);$('zoom-out').onclick=()=>world.zoom(1/1.22);$('rotate-view').onclick=()=>world.rotate();$('home-view').onclick=()=>world.home();
  $('close-dialogue').onclick=closeDialogue;
  world.addEventListener('ambient',e=>{if(panel.open||placing||mode==='decorate')return;const b=$('ambient-greeting');b.textContent=e.detail.name+'：'+e.detail.line;b.hidden=false;b.onclick=()=>{b.hidden=true;openDialogue(e.detail.id);};clearTimeout(ambientTimer);ambientTimer=setTimeout(()=>b.hidden=true,8000);});
  world.addEventListener('npc',e=>openDialogue(e.detail));world.addEventListener('member',e=>openMember(e.detail));world.addEventListener('hint',e=>toast(e.detail));world.addEventListener('selectitem',e=>openPlaced(e.detail));world.addEventListener('zone',e=>$('location-label').textContent=e.detail);world.addEventListener('ghostchange',e=>updateGhostUI(e.detail));world.addEventListener('error',e=>toast(e.detail,true));
  window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||panel.open)return;if(e.key==='Escape'){if(placing)cancelPlacement();else if(activeNpc)closeDialogue();else if(mode==='decorate')setMode('walk');}if(e.code==='KeyR'&&placing)world.rotateGhost();if(e.code==='Enter'&&placing){e.preventDefault();confirmPlacement();}if((e.ctrlKey||e.metaKey)&&e.code==='KeyZ'&&mode==='decorate'){e.preventDefault();(e.shiftKey?$('redo-button'):$('undo-button')).click();}if(e.code==='Space'&&placing)e.preventDefault();});
  installNavigation({dirty,isPlacing:()=>!!placing,save:()=>{if(placing)cancelPlacement();return saveLayout();},prompt:actions=>{
    openPanel('先把喜歡的佈置留下來','BEFORE WE SET OFF',`<p>還有尚未儲存的佈置。儲存完成後，就會前往你選的小島。</p><div class="button-row"><button id="travel-save" class="primary-button">儲存後前往</button><button id="travel-stay" class="secondary-button">留在小島</button><button id="travel-discard" class="secondary-button">捨棄此次修改並前往</button></div>`);
    $('travel-save').onclick=async()=>{const button=$('travel-save');button.disabled=true;button.textContent='正在儲存…';try{await actions.save();}finally{if(button.isConnected){button.disabled=false;button.textContent='儲存後前往';}}};
    $('travel-stay').onclick=closePanel;$('travel-discard').onclick=actions.discard;
  }});
  window.addEventListener('storage',e=>{if(config.cloud||e.key!==store.key)return;if(dirty()){toast('另一個分頁有更新。請先在手帳匯出目前佈置，再重新整理。',true);return;}run(async()=>{store.state=store.read()||store.state;history.rebase(store.layout());world.updateProgress(store.state);world.renderPlacements(store.state.placements);world.setTime(store.state.time);refresh();toast('已載入另一個分頁儲存的小島。');});});
}
function setMode(next){
  if(next==='decorate'&&!editable())return;closeDialogue();if(placing)cancelPlacement();mode=next;if(next!=='decorate'){thumbObserver?.disconnect();thumbGeneration++;}document.body.classList.toggle('editing',next==='decorate');$('decor-tray').hidden=next!=='decorate';document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===next));world.setMode(next);if(next==='decorate'){collection='inventory';category='全部';renderTray();}chirp();
}
function renderTray(){
  thumbObserver?.disconnect();const generation=++thumbGeneration;let thumbQueue=[],thumbPending=false;const pump=()=>{thumbPending=false;if(generation!==thumbGeneration)return;const img=thumbQueue.shift();if(img?.isConnected)img.src=thumbs.item(img.dataset.thumb);if(thumbQueue.length){thumbPending=true;requestAnimationFrame(pump);}};thumbObserver=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting){thumbQueue.push(e.target);thumbObserver.unobserve(e.target);}if(thumbQueue.length&&!thumbPending){thumbPending=true;requestAnimationFrame(pump);}},{root:$('item-list'),rootMargin:'0px 160px'});
  document.querySelectorAll('[data-collection]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.collection===collection)));
  $('categories').innerHTML=CATEGORIES.map(c=>`<button class="${category===c?'active':''}" data-category="${c}">${c}</button>`).join('');$('categories').querySelectorAll('button').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderTray();});
  let rows;
  if(collection==='shop')rows=Object.values(CATALOG).map(item=>({item,sub:'100 點'}));
  else if(collection==='placed')rows=Object.entries(history.present.placements).map(([key,p])=>({item:CATALOG[p.itemId],key,sub:'移動 · 收回'}));
  else rows=Object.entries(history.present.inventory).filter(([,n])=>n>0).map(([id,count])=>({item:CATALOG[id],count,sub:'拿起來佈置'}));
  rows=rows.filter(r=>category==='全部'||r.item.category===category);
  $('item-list').innerHTML=rows.length?rows.map((r,i)=>`<button class="item-card" data-row="${i}" aria-label="${esc(r.item.name)} · ${r.sub}">${r.count?`<span class="item-count">× ${r.count}</span>`:''}<img data-thumb="${r.item.id}" alt="${esc(r.item.name)}的 3D 模型"><b>${esc(r.item.name)}</b><small>${r.sub}</small></button>`).join(''):`<div class="empty-state">${collection==='inventory'?'這個分類還沒有家具。<br>去島嶼商店看看，或完成島民的小心願。':collection==='placed'?'這裡還沒有佈置。<br>從收納裡挑一件喜歡的家具吧。':'這個分類還沒有家具。'}</div>`;
  $('item-list').querySelectorAll('[data-thumb]').forEach(img=>thumbObserver.observe(img));
  $('item-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{const r=rows[Number(b.dataset.row)];if(collection==='shop')openItem(r.item.id);else if(collection==='placed')openPlaced(r.key);else startPlacement(r.item.id);});
  $('tray-help').textContent=collection==='shop'?'每件家具 100 點。購買後放進收納，團隊總分不會減少。':'點物品拿取 · 點地面選位置 · R 旋轉 · 拖曳仍可轉動鏡頭';
}
function openPanel(title,kicker,html){closeDialogue();if(modelPreview){modelPreview.dispose();modelPreview=null;}if(!panel.open)lastPanelFocus=document.activeElement;$('panel-title').textContent=title;$('panel-kicker').textContent=kicker;$('panel-body').innerHTML=html;hydrateIcons($('panel-body'));if(!panel.open)panel.showModal();}
function closePanel(){panel.close();}
function openItem(id){
  const item=CATALOG[id];openPanel(item.name,'ISLAND COLLECTION',`<div class="item-detail"><div><div id="item-model" class="item-model"></div><small>拖曳轉動，看看每個細節</small></div><div><small>${item.category} · ${THEMES[config.group-1].name}選物</small><p>${item.description}</p><div class="item-price">100 <small>點</small></div><p class="panel-footnote">目前持有 ${history.present.inventory[id]||0} 件</p></div></div><div class="button-row"><button id="item-back" class="secondary-button">再逛逛</button>${!config.viewer?`<button id="buy-item" class="primary-button" ${store.state.spendablePoints<100?'disabled':''}>${icon('plus')}購買並佈置</button>`:''}</div>`);
  modelPreview=new ModelPreview($('item-model'),id);$('item-back').onclick=closePanel;if($('buy-item'))$('buy-item').onclick=()=>run(async()=>{if(!editable())return;await store.buy(id);const next=clone(history.present);next.inventory[id]=(next.inventory[id]||0)+1;history.rebase(next);closePanel();refresh();chirp('success');startPlacement(id);toast(`${item.name} 已放進收納，找個喜歡的位置吧。`);});
}
function startPlacement(id,key=null){
  if(!editable())return;if(mode!=='decorate')setMode('decorate');closePanel();closeDialogue();
  const p=key?history.present.placements[key]:null;if(!p&&(history.present.inventory[id]||0)<1){toast('收納裡已經沒有這件家具了。');return;}
  placing={id,key};document.body.classList.add('placing');$('placement-toolbar').hidden=false;$('placing-thumb').src=thumbs.item(id);$('placing-name').textContent=CATALOG[id].name;$('snap-button').setAttribute('aria-pressed','true');world.startGhost(id,p,p?.rot||0,key);refresh();
}
function updateGhostUI(p){if(!p)return;$('placing-status').textContent=!p.chosen?'點一下地面，選好位置。':p.reason;$('placing-status').parentElement.classList.toggle('invalid',!p.ok);$('confirm-item').disabled=!(p.ok&&p.chosen);}
function cancelPlacement(){world.clearGhost();placing=null;document.body.classList.remove('placing');$('placement-toolbar').hidden=true;refresh();}
function confirmPlacement(){
  if(!placing||!editable())return;const p=world.ghostState();if(!p?.chosen||!p.ok){toast(p?.chosen?p.reason:'先點一下地面，選好位置。');return;}
  run(async()=>{const selected={...placing};history.apply(layout=>{let key=selected.key;if(!key){for(let i=0;i<128;i++)if(!layout.placements[String(i)]){key=String(i);break;}if(key===undefined||key===null)throw new Error('已達 128 件家具，收回一些再試試。');if((layout.inventory[selected.id]||0)<1)throw new Error('收納裡沒有這件家具。');layout.inventory[selected.id]--;}
      layout.placements[key]={itemId:selected.id,x:p.x,z:p.z,rot:p.rot};});
    cancelPlacement();world.renderPlacements(history.present.placements);refresh();chirp('success');toast('放好了！可以繼續調整，最後記得儲存佈置。');});
}
function openPlaced(key){const p=history.present.placements[key];if(!p)return;const item=CATALOG[p.itemId];openPanel(item.name,'A PLACE OF ITS OWN',`<div class="item-detail"><img src="${thumbs.item(item.id)}" alt="${item.name}"><div><small>已佈置在島上</small><p>${item.description}</p></div></div><div class="button-row"><button id="collect-item" class="secondary-button">收回收納</button><button id="move-item" class="primary-button">${icon('edit')}換個位置</button></div>`);$('move-item').onclick=()=>startPlacement(p.itemId,key);$('collect-item').onclick=()=>run(async()=>{if(!editable())return;history.apply(l=>{l.inventory[p.itemId]=(l.inventory[p.itemId]||0)+1;delete l.placements[key];});world.renderPlacements(history.present.placements);closePanel();refresh();toast('已收回收納，儲存後會保留這次調整。');});}
function saveLayout(){return run(async()=>{if(!editable()||placing)return false;await store.saveLayout(history.present);history.rebase(store.layout());world.renderPlacements(store.state.placements);const gifts=[];for(const id of ['bench','explore','lantern','teaTable','musicStage','telescope']){const q=await completeQuest(id,true);if(q)gifts.push(q);}refresh();chirp('success');toast(gifts.length?'佈置已儲存 · 收到 '+gifts.map(q=>q.reward+' · +50 分').join('、'):config.cloud?'小島佈置已儲存，其他裝置也能看見。':'小島佈置已儲存在這台電腦。');if(gifts.length)openRewards(gifts);return true;});}
function completeQuest(id,quiet=false,evidence={}){if(config.viewer)return;return run(async()=>{const q=await store.complete(id,evidence);if(q){const next=clone(history.present);next.inventory[q.gift]=(next.inventory[q.gift]||0)+1;history.rebase(next);world.updateProgress(store.state);refresh();if(!quiet){openRewards([q]);chirp('success');}}return q;});}
function openDialogue(id){
  $('ambient-greeting').hidden=true;
  if(placing)return;if(mode==='decorate')setMode('walk');closeDialogue();const npc=NPCS.find(n=>n.id===id);if(!npc||!availableNpcs(store.state.progressScore).some(n=>n.id===id))return;activeNpc=id;world.talk(id,true);
  if(!config.viewer)run(async()=>{if(!store.state.met.includes(id))await store.meet(id);const chat=await store.chat(id);const q=await completeQuest('hello',true);world.updateProgress(store.state);refresh();if(q||chat)openRewards(q?[q]:[],chat?.amount||0);});
  const fulfilled=Object.values(store.state.placements).some(p=>p.itemId===npc.item);
  $('dialogue-portrait').src=thumbs.npc(npc);$('dialogue-portrait').alt=npc.name;$('npc-name').textContent=npc.name;$('npc-role').textContent=npc.role;
  const turn=dialogueTurns.get(id)||0;dialogueTurns.set(id,turn+1);$('npc-words').textContent=npcDialogue(npc,store.state,turn)+'\n\n'+npcRequest(npc,store.state);
  $('dialogue-actions').className='dialogue-actions';$('dialogue-actions').innerHTML=`<button id="npc-farewell" class="secondary-button">等一下見</button><button id="npc-chat" class="secondary-button">聊聊今天</button>${!config.viewer?`<button id="npc-help" class="primary-button">${store.state.quests[npc.item]?'看看島上日常':fulfilled?'領取建設禮物':'我想幫忙'}</button>`:''}`;$('npc-farewell').onclick=closeDialogue;$('npc-chat').onclick=()=>openDialogue(id);
  if($('npc-help'))$('npc-help').onclick=()=>run(async()=>{closeDialogue();if(store.state.quests[npc.item])openJournal();else if(fulfilled){await completeQuest(npc.item);}else{setMode('decorate');if((history.present.inventory[npc.item]||0)>0)startPlacement(npc.item);else{collection='shop';category=CATALOG[npc.item].category;renderTray();openItem(npc.item);}}});
  $('dialogue').hidden=false;chirp();
}
function closeDialogue(){if(activeNpc)world?.talk(activeNpc,false);activeNpc=null;$('dialogue').hidden=true;}
function openResidents(){
  if(config.leader){openTeam();return;}
  openPanel('住在這裡的朋友','NEIGHBORS & LITTLE STORIES',`<p class="panel-footnote">居民會散步、賞花、坐下休息，也會搭乘你放置的遊樂設施。</p>${[...NPCS].filter(n=>!config.viewer||(n.unlock||0)<=store.state.progressScore).sort((a,b)=>(a.unlock||0)-(b.unlock||0)).map(n=>{const ready=(n.unlock||0)<=store.state.progressScore;return `<div class="resident-card ${ready?'':'locked'}"><img src="${thumbs.npc(n)}" alt="${n.name}的立體造型"><div class="resident-info"><h3>${n.name} <small>${ready?(store.state.met.includes(n.id)?'已認識':'新鄰居'):'準備搬來'}</small></h3><small>${n.role}</small><p>${ready?n.request:`${n.unlock} 分 · 和新土地一起到來`}</p></div>${ready?`<button data-visit="${n.id}">聊聊天</button>`:'<span class="lock-mark">待解鎖</span>'}</div>`;}).join('')}<div class="button-row"><button id="team-button" class="secondary-button">看看團隊小精靈</button></div>`);
  $('panel-body').querySelectorAll('[data-visit]').forEach(b=>b.onclick=()=>{closePanel();openDialogue(b.dataset.visit);});$('team-button').onclick=openTeam;
}
function openJournal(){
  const count=Object.keys(store.state.quests).length;openPanel('小島生活手帳','LITTLE THINGS, LOVELY DAYS',`<div class="journal-intro"><p>已留下 <b>${count} / ${QUESTS.length}</b> 個小小的日常。<br>完成每個心願會收到家具與 50 分。每位 NPC 每天首次聊天，全組另得 5 分。</p></div>${QUESTS.map((q,i)=>`<div class="quest-row ${store.state.quests[q.id]?'done':''}"><span>${store.state.quests[q.id]?'✓':String(i+1).padStart(2,'0')}</span><div><h3>${q.title}</h3><p>${q.detail}</p><small>${store.state.quests[q.id]?'已收到':'小禮物'} · ${q.reward} · +50 分</small></div>${!store.state.quests[q.id]?`<button class="secondary-button" data-quest="${q.id}" aria-label="前往：${q.title}">${icon('arrow')}</button>`:''}</div>`).join('')}<div class="button-row"><button id="export-button" class="secondary-button">${icon('download')}匯出佈置與草稿</button></div><p class="panel-footnote">${config.cloud?'這本手帳與小島會同步儲存。匯出也會保留尚未儲存的佈置草稿。':'這本手帳屬於本機預覽，資料只存在目前瀏覽器。'}</p>`);
  $('panel-body').querySelectorAll('[data-quest]').forEach(b=>b.onclick=()=>{let id=b.dataset.quest;const q=QUESTS.find(q=>q.id===id);if(store.state.progressScore<(q.unlock||0)){toast(`${q.unlock} 分後，新居民會帶著這個心願來訪。`);return;}closePanel();if(id==='hello')openResidents();else if(id==='photo')takePhoto();else{if(id==='explore')id='flowerPatch';setMode('decorate');if((history.present.inventory[id]||0)>0)startPlacement(id);else openItem(id);}});
  $('export-button').onclick=()=>download(`${store.state.worldName}-${config.room}-本機佈置.json`,new Blob([JSON.stringify({...store.state,...clone(history.present),exportedAt:new Date().toISOString(),source:config.cloud?'emotion-island-v4':'local-preview-only'},null,2)],{type:'application/json'}));
}
function openMap(){const zones=config.leader?[{id:'palace',name:'星願大殿',subtitle:'主殿與兩翼星宮',x:-2,z:-18,zoom:.8},{id:'court',name:'星宮前庭',subtitle:'星環光泉與儀式大道',x:-2,z:7,zoom:1.0},{id:'moon',name:'月鏡水庭',subtitle:'月光、涼亭與湖畔茶席',x:31,z:1,zoom:.9},{id:'fair',name:'雲端遊樂園',subtitle:'摩天輪與天空飛椅',x:-39,z:1,zoom:.8},{id:'fest',name:'星河慶典地',subtitle:'列車、樂台與旋轉木馬',x:0,z:34,zoom:.68},{id:'library',name:'守望書院',subtitle:'書香、花園與北境瀑布',x:-38,z:-21,zoom:.9},{id:'all',name:'看見整座神境',subtitle:'每一處，都已為你佈置好',x:0,z:0}]:ZONES;openPanel('把目光，交給小島','PLACES TO MAKE YOUR OWN',`<div class="map-tools"><span>跟著小徑，走進今天的風景。</span><button id="map-time" class="secondary-button">光線 · ${{day:'晴日',sunset:'夕照',night:'星夜'}[store.state.time]}</button></div><canvas id="large-map" class="map-main" width="720" height="490" aria-label="小島地圖"></canvas><div class="map-legend"><span><i style="--dot:#a88e66"></i>建築與地標</span><span><i style="--dot:#597b59"></i>樹木</span><span><i style="--dot:#f0ddb0"></i>小精靈</span>${(config.leader?[]:availableNpcs(store.state.progressScore)).map(n=>`<span><i style="--dot:${n.color}"></i>${n.name}</span>`).join('')}</div><div class="zone-list">${zones.map((z,i)=>`<button data-zone="${z.id}"><span>${String(i+1).padStart(2,'0')}</span><div><b>${i===0&&!config.leader?THEMES[config.group-1].title:z.name}</b><small>${z.subtitle}</small></div></button>`).join('')}</div><p class="panel-footnote">點區域移動鏡頭。拖曳旋轉、右鍵或雙指平移、滾輪縮放。方向鍵也能移動鏡頭。</p>`);world.drawMiniMap($('large-map'),true);$('map-time').onclick=()=>{$('time-button').click();$('map-time').textContent='光線 · '+{day:'晴日',sunset:'夕照',night:'星夜'}[store.state.time];};$('panel-body').querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>{closePanel();const z=zones.find(z=>z.id===b.dataset.zone);if(z.id==='all')world.home();else world.focus(z);});}
function openMember(id){const n=world.members.find(n=>n.id===String(id));if(!n)return;const a=memberAppearance(store.state,id);openPanel(a.name,config.leader?'KEEPERS OF THE STAR GARDEN':'A LITTLE SOUL, A LITTLE STORY',`<div class="item-detail"><div id="member-model" class="item-model"></div><div><p>${n.activity?'正在享受島上的佈置':n.path.length?'正在小島上散步':'正在享受悠閒的時光'}。</p><p>每一個被記住的名字，都讓這裡更像家。</p></div></div><div class="button-row"><button id="find-member" class="secondary-button">看看現在的樣子</button>${!config.viewer?'<button id="edit-member" class="primary-button">命名與換裝</button>':''}</div>`);modelPreview=new ModelPreview($('member-model'),a);$('find-member').onclick=()=>{closePanel();world.focus({x:n.object.position.x,z:n.object.position.z,zoom:2.4,name:a.name});};if($('edit-member'))$('edit-member').onclick=()=>openAvatar(id);}
function openAvatar(memberId=1){
  if(!editable())return;const count=Math.min(store.state.maxMembers,Math.floor(store.state.progressScore/100));if(Number(memberId)>count)return;let avatar=memberAppearance(store.state,memberId);const palettes={outfit:['#dd9069','#8aa58b','#8fa9bf','#d7b374','#b19daf','#e5c3ad'],hair:['#4d332b','#876443','#bb9165','#657782'],skin:['#f1c6a0','#dfae87','#bd8967','#93684e']};
  openPanel('替夥伴，留一點自己的樣子','A NAME, A LITTLE PERSONALITY',`<div class="avatar-editor"><img id="avatar-preview" src="${thumbs.avatar(avatar)}" alt="小精靈造型預覽"><div><label class="form-label" for="avatar-name-input">這位小精靈的名字</label><input id="avatar-name-input" class="text-input" maxlength="18" value="${esc(avatar.name)}">${Object.entries(palettes).map(([key,cs])=>`<label class="form-label">${{outfit:'喜歡的衣服',hair:'頭髮顏色',skin:'膚色'}[key]}</label><div class="swatches">${cs.map((c,i)=>`<button style="--swatch:${c}" class="${avatar[key]===c?'selected':''}" data-appearance="${key}" data-color="${c}" aria-label="${{outfit:'衣服',hair:'頭髮',skin:'膚色'}[key]} ${i+1}" aria-pressed="${avatar[key]===c}"></button>`).join('')}</div>`).join('')}<label class="form-label">髮型</label><div class="style-options">${[['bob','柔軟短髮'],['bun','丸子頭'],['crop','俐落短髮']].map(([k,n])=>`<button data-hair-style="${k}" class="${avatar.style===k?'selected':''}">${n}</button>`).join('')}</div></div></div><div class="button-row"><button id="save-avatar" class="primary-button">記住這個樣子</button></div>`);
  $('panel-body').querySelectorAll('[data-appearance]').forEach(b=>b.onclick=()=>{avatar[b.dataset.appearance]=b.dataset.color;for(const s of $('panel-body').querySelectorAll(`[data-appearance="${b.dataset.appearance}"]`)){const on=s===b;s.classList.toggle('selected',on);s.setAttribute('aria-pressed',String(on));}$('avatar-preview').src=thumbs.avatar(avatar);});
  $('panel-body').querySelectorAll('[data-hair-style]').forEach(b=>b.onclick=()=>{avatar.style=b.dataset.hairStyle;$('panel-body').querySelectorAll('[data-hair-style]').forEach(el=>el.classList.toggle('selected',el===b));$('avatar-preview').src=thumbs.avatar(avatar);});
  $('save-avatar').onclick=()=>run(async()=>{avatar.name=$('avatar-name-input').value.trim()||`小精靈 ${memberId}`;const members=clone(store.state.members);members[String(memberId)]=avatar;await store.update({members});world.updateMembers(store.state);refresh();closePanel();chirp('success');toast('小精靈有了新的名字與樣子。');});
}
function renameIsland(){if(!editable())return;openPanel('給小島一個名字','SOMEWHERE TO CALL HOME',`<label for="new-island-name" class="form-label">我的小島叫做</label><input id="new-island-name" class="text-input" maxlength="20" value="${esc(store.state.worldName)}"><div class="button-row"><button id="rename-confirm" class="primary-button">記住這個名字</button></div>`);$('rename-confirm').onclick=()=>run(async()=>{const name=$('new-island-name').value.trim();if(!name)throw new Error('先替小島想個名字吧。');await store.update({worldName:name});refresh();closePanel();});}
function openGrowth(){if(!editable())return;const s=store.state,g=growthFor(s.progressScore);openPanel('一起長大的小世界','OUR LITTLE PROGRESS',`<div class="stat-grid"><div class="stat-box"><b>${s.score.toLocaleString()}</b><small>活動加分</small></div><div class="stat-box"><b>${(s.rewardScore||0).toLocaleString()}</b><small>獎勵分數</small></div><div class="stat-box"><b>${totalScore(s).toLocaleString()}</b><small>排名總分</small></div><div class="stat-box"><b>${s.spendablePoints.toLocaleString()}</b><small>可佈置的點數</small></div></div><div class="growth-status"><b>${g.label} · 第 ${g.stage+1} 階段</b><span>${g.next?`距下一片新土地，還有 ${Math.max(0,g.next-s.progressScore)} 分`:'完整島嶼已開放，分數仍可繼續累積'}</span><progress max="1600" value="${Math.min(1600,s.progressScore)}"></progress></div><div class="growth-milestones">${[[0,'初遇','苔米與溪光草坪'],[400,'甦醒','東岸新草坪 · 小陶'],[800,'繁盛','西邊花園地 · 露朵'],[1200,'奇境','後山觀星地 · 花穗'],[1600,'完整','南岸慶典地 · 阿嵐']].map(([p,n,d])=>`<div class="${s.progressScore>=p?'reached':''}"><b>${p}</b><span>${n}</span><small>${d}</small></div>`).join('')}</div><p>每 100 分增加一位小精靈。每 400 分增加土地和新居民；主畫面的島嶼也隨著分數升高。買家具只花佈置點數。</p><div class="life-summary"><b>島上的生活節奏</b><p>現在有 ${g.npcCount} 位 NPC，全島約每 ${lifeFor(s.progressScore).label} 出現一次主動招呼。點居民隨時都能聊天。</p><div class="life-levels">${LIFE_STAGES.map((p,i)=>`<div><b>${i*400} 分</b><span>${i+1} 位 NPC</span><span>${p.label}／次</span></div>`).join('')}</div><p class="panel-footnote">只計算停留在島上觀察的時間；佈置、開啟面板與切到背景時會暫停招呼。居民碰面互動也會隨階段增加。每個心願每組領取一次家具與 50 分；每位 NPC 每天首次聊天全組 +5 分，以臺灣時間換日。</p></div><form id="score-form" class="score-form"><label class="form-label" for="score-input">本次加分</label><p>活動房號 ${config.room} · 新成立的小島贈送 1,000 點佈置點數</p><div class="score-row"><input id="score-input" class="text-input" type="number" min="1" max="100000" step="1" placeholder="例如 100" required><button class="primary-button" type="submit">加入這份努力</button></div></form><div class="button-row"><button id="growth-team" class="secondary-button">團隊小精靈</button></div>`);$('score-form').onsubmit=e=>{e.preventDefault();run(async()=>{if(!editable())return;const amount=Number($('score-input').value),stage=growthFor(store.state.progressScore).stage;await store.addScore(amount);world.updateProgress(store.state);refresh();closePanel();chirp('success');toast(growthFor(store.state.progressScore).stage>stage?`累積 ${amount} 分 · 新土地與新鄰居已抵達！`:`一起累積了 ${amount} 分，小島更熱鬧了。`);});};$('growth-team').onclick=openTeam;}
function openTeam(){
  const s=store.state,n=Math.min(s.maxMembers,Math.floor(s.progressScore/100));openPanel(config.leader?'守護星願的八位夥伴':'一起生活的小精靈',config.leader?'KEEPERS OF THE STAR GARDEN':'YOUR TEAM, YOUR ISLAND',`${!config.viewer?'<label class="form-label" for="member-cap">本組人數（1～30）</label><input id="member-cap" class="text-input" type="number" min="1" max="30" value="'+s.maxMembers+'">':''}<p>${config.leader?'他們在神境裡散步、休息，也會輪流乘上遊樂設施。':config.viewer?'每個小精靈都有自己的名字與生活。':`目前已解鎖 ${n} 位，每 100 分增加一位，最多依本組設定人數。`}</p><div class="team-grid">${Array.from({length:n},(_,i)=>{const a=memberAppearance(s,i+1);return `<button class="team-card" data-member="${i+1}"><img src="${thumbs.avatar(a)}" alt="${esc(a.name)}的造型"><b>${esc(a.name)}</b><small>${config.viewer?'看看近況':'命名 · 換裝 · 近況'}</small></button>`;}).join('')||'<div class="empty-state">下一個 100 分，就會迎來第一位小精靈。<br>先替夥伴佈置好喜歡的角落吧。</div>'}</div>${!config.viewer?'<div class="button-row"><button id="save-team" class="primary-button">儲存本組人數</button></div>':''}`);
  $('panel-body').querySelectorAll('[data-member]').forEach(b=>b.onclick=()=>openMember(b.dataset.member));
  if($('save-team'))$('save-team').onclick=()=>run(async()=>{if(!editable())return;const cap=Number($('member-cap').value);if(!Number.isInteger(cap)||cap<1||cap>30)throw new Error('本組人數請填 1～30。');await store.update({maxMembers:cap});world.updateMembers(store.state);refresh();openTeam();toast('已記住本組人數，夥伴名字會保留。');});
}
function openIslands(){openPanel('沿著風，拜訪彼此','EIGHT ISLANDS, ONE SHARED SKY',`<p class="panel-footnote">${config.ownerGroup?`你可以佈置第 ${config.ownerGroup} 組的小島，其他島嶼都是唯讀參觀。`:"這趟旅程是唯讀參觀，所有島嶼都不能修改。"}島內地圖由下方「地圖」開啟。</p><div class="travel-links"><a class="primary-button" href="${pageHref(config,'emotion_island.html')}">前往不孤島</a><a class="secondary-button" href="${pageHref(config,'emotion_leader_world.html')}">主領班 · 星願神境</a></div><div class="island-picker">${THEMES.map(t=>`<a href="${visitorHref(t.id)}" style="--island-color:${t.color}"><span>${String(t.id).padStart(2,'0')}</span><div><b>${t.name}${config.ownerGroup===t.id?' · 回自己的島':''}</b><small>${t.subtitle}</small></div>${icon('arrow')}</a>`).join('')}</div><p class="panel-footnote">唯讀連結可以觀察、聊天、拍照，無法加分或修改佈置。${config.cloud?'這裡會載入活動中各組最新儲存的小島。':'這份預覽的資料只存在同一台電腦、同一個瀏覽器。'}</p>`);}
async function takePhoto(){if(placing){toast('先放下家具，畫面會更漂亮。');return;}const photo=world.photo();const gift=await completeQuest('photo',true,{photographed:true});openPanel('把這一刻，留下來','A POSTCARD FROM YOUR ISLAND',`${gift?`<p class="photo-reward">收到 ${gift.reward} · 獎勵分數 +50 分</p>`:''}<img class="photo-preview" src="${photo}" alt="${esc(store.state.worldName)}的小島照片"><div class="button-row"><button id="photo-again" class="secondary-button">再找個角度</button><button id="download-photo" class="primary-button">${icon('download')}保存照片</button></div>`);$('photo-again').onclick=closePanel;$('download-photo').onclick=()=>{const a=document.createElement('a');a.href=photo;a.download=`${store.state.worldName}-${config.room}-${Date.now()}.png`;a.click();chirp('success');};}
function download(filename,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
const bgm=new Audio('assets/island-music.mp3');bgm.loop=true;bgm.volume=.18;
async function toggleMusic(){try{if(bgm.paused){await bgm.play();$('sound-button').innerHTML=icon('sound');$('sound-button').classList.add('playing');$('sound-button').setAttribute('aria-label','關閉島嶼音樂');}else{bgm.pause();$('sound-button').innerHTML=icon('sound-off');$('sound-button').classList.remove('playing');$('sound-button').setAttribute('aria-label','開啟島嶼音樂');}}catch{toast('音樂還沒準備好，稍後再試一次。',true);}}

function openRewards(quests=[],chatBonus=0){
  openPanel('小島收到一份心意','A LITTLE THANK YOU',`<p>謝謝你替這座島留下新的生活。</p>${quests.map(q=>`<div class="reward-row"><img src="${thumbs.item(q.gift)}" alt="${esc(q.reward)}"><div><b>${esc(q.title)}</b><p>收到 ${esc(q.reward)}</p><strong>獎勵分數 +${q.scoreReward} 分</strong></div></div>`).join('')}${chatBonus?`<div class="chat-reward"><b>今天第一次和這位居民聊天</b><strong>獎勵分數 +${chatBonus} 分</strong><p>同一位 NPC 的聊天獎勵每天全組領一次，明天再來聊聊吧。</p></div>`:''}<p class="panel-footnote">獎勵分數會加進排名總分與成長進度，並增加可用點數；活動加分保持獨立。</p><div class="button-row"><button id="reward-close" class="primary-button">收下心意</button></div>`);
  $('reward-close').onclick=closePanel;
}
