import {sessionConfig,pageHref,visitScope,islandHref} from './session.js';
import {readRoom,watchRoom,stateFromRoot} from './cloud.js';
import {THREE,mat,mesh,ball,box,cylinder,link,curve,makeTree,makePine,makeCottage,decor,batchStatic,seeded,disposeModel} from './models.js';
import {OrbitControls} from '../vendor/OrbitControls.js';
import {THEMES,IslandStore,parsePreviewRoom,growthFor,initialState,totalScore,islandElevation} from './state.js';
import {Thumbnails} from './world.js';
import {animateDecor} from './extra-models.js';
import {hydrateIcons,icon} from './icons.js';

const $=id=>document.getElementById(id),escape=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
hydrateIcons();let config,renderer,scene,camera,controls,sun,hemi,ocean,thumbs,selected=null,night=false,states=[],islands=[],labels=[],clouds=[],birds=[],bridges=[],lastTime=performance.now(),time=0;
const compact=innerWidth<700||(matchMedia('(pointer:coarse)').matches&&innerWidth<1180),reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;let drawCount=0,lastDraw=0,renderMean=0,sceneWidth=1280,sceneHeight=720;
const panel=$('panel-dialog'),heroes=['leaderStarFountain','torii','giantTree','windmill','moonLamp','musicStage','crystal','leaderPalace'];
try{config=visitScope({...sessionConfig(location.search,location.hostname),viewer:true},sessionStorage,location.search,false);if(config.cloud){const root=await readRoom(config.room);states=THEMES.map(t=>stateFromRoot(root,config.room,t.id));}start();if(config.cloud)watchRoom(config.room,root=>{states=THEMES.map(t=>stateFromRoot(root,config.room,t.id));islands.forEach((_,i)=>syncIsland(i));if(selected)selectIsland(selected);},e=>notify(e.message),{interval:2500});}catch(e){$('loading').hidden=true;$('boot-error').hidden=false;$('boot-error-message').textContent=e.message;console.error(e);}

function readStates(){if(config.cloud)return;states=THEMES.map(t=>{try{return new IslandStore(localStorage,t.id,true).state;}catch(e){notify(`${t.name} 的本機存檔需要確認，原始資料已保留。`);return initialState(t.id);}});}
function notify(text){$('toast-region').innerHTML=`<div class="toast">${escape(text)}</div>`;setTimeout(()=>$('toast-region').replaceChildren(),5000);}
function start(){
  document.title='共感大世界 — 情緒不孤島 · '+config.room;
  document.querySelector('.preview-tag').textContent=(config.cloud?'活動房號 · ':'本機預覽 · ')+config.room;document.querySelectorAll('a[href]').forEach(a=>{const u=new URL(a.href);if(u.origin===location.origin&&u.searchParams.has('room'))a.href=pageHref(config,u.pathname.split('/').pop());});
  readStates();thumbs=new Thumbnails();scene=new THREE.Scene();scene.background=new THREE.Color('#91b6b0');scene.fog=new THREE.Fog('#aac6ba',165,360);
  renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:false});renderer.outputEncoding=THREE.sRGBEncoding;renderer.toneMapping=THREE.LinearToneMapping;renderer.toneMappingExposure=.98;renderer.setPixelRatio(Math.min(devicePixelRatio,compact?1.3:1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.autoUpdate=false;renderer.shadowMap.type=THREE.PCFSoftShadowMap;$('scene').appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','拖曳轉動共感群島，點島嶼參觀');
  camera=new THREE.OrthographicCamera(-60,60,45,-45,.1,500);camera.position.set(66,94,110);controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,4,0);controls.enableDamping=true;controls.minPolarAngle=.45;controls.maxPolarAngle=1.16;controls.minZoom=.6;controls.maxZoom=2.5;controls.rotateSpeed=.42;controls.zoomSpeed=.8;
  hemi=new THREE.HemisphereLight('#e1e9df','#8b998b',.79);scene.add(hemi);sun=new THREE.DirectionalLight('#fff0d2',1.08);sun.position.set(-55,100,35);sun.castShadow=true;sun.shadow.mapSize.set(compact?1024:2048,compact?1024:2048);Object.assign(sun.shadow.camera,{left:-66,right:66,top:66,bottom:-66,near:1,far:230});sun.shadow.bias=-.0003;sun.shadow.normalBias=.09;scene.add(sun);const fill=new THREE.DirectionalLight('#abcbd5',.3);fill.position.set(40,30,-20);scene.add(fill);
  makeOcean();THEMES.forEach(makeIsland);makeCenter();makeSky();resize();wire();requestAnimationFrame(draw);window.islandReady=true;$('loading').classList.add('leaving');setTimeout(()=>$('loading').hidden=true,600);
}
function islandBase(theme,r=6.6){
  const g=new THREE.Group(),n=72;const ring=(radius,y,shade)=>{const shape=new THREE.Shape();for(let i=0;i<=n;i++){const a=i/n*Math.PI*2,rr=radius*(1+.055*Math.sin(a*3+theme.id)+.035*Math.cos(a*5));if(!i)shape.moveTo(Math.cos(a)*rr,Math.sin(a)*rr*.83);else shape.lineTo(Math.cos(a)*rr,Math.sin(a)*rr*.83);}const m=mesh(g,new THREE.ExtrudeGeometry(shape,{depth:y,bevelEnabled:true,bevelSegments:3,steps:1,bevelSize:.16,bevelThickness:.18}),mat(shade));m.rotation.x=-Math.PI/2;return m;};
  const grass=ring(r,.3,theme.grass);grass.position.y=.2;const earth=ring(r*1.01,.58,'#ae9b78');earth.position.y=-.43;const cliff=ring(r*.97,1.1,'#978d73');cliff.position.y=-1.47;const sand=ring(r*1.035,.2,'#cbbb96');sand.position.y=-1.76;
  mesh(g,new THREE.ConeGeometry(r*.89,4.0,11),mat('#85968a'),0,-3.65,0,1,1,.83).rotation.z=Math.PI;
  const rng=seeded(theme.id*512);for(let i=0;i<16;i++){const a=rng()*Math.PI*2;ball(g,i%2?'#9da28a':'#b8b096',Math.sin(a)*r*.88,-1.5-rng()*1.5,Math.cos(a)*r*.75,.7+rng()*.5,.35+rng()*.4,.5+rng()*.2);}
  return g;
}
function makeIsland(theme,index){
  const angle=index*Math.PI/4-Math.PI*.66,radius=33.5,g=new THREE.Group(),base=islandBase(theme),staticRoot=new THREE.Group();g.add(base,staticRoot);const a=angle,x=Math.sin(a)*radius,z=Math.cos(a)*radius*.84;g.position.set(x,islandElevation(totalScore(states[index])).height,z);g.rotation.y=-a*.25;g.userData.group=theme.id;scene.add(g);
  const home=makeCottage(theme.roof);home.scale.setScalar(.58);home.position.set(-1.8,.57,-.75);staticRoot.add(home);const hero=decor(heroes[index]);hero.position.set(2.4,.55,-1.05);hero.scale.setScalar(theme.landmark==='crystal'?1.1:theme.landmark==='forest'?.62:.72);g.add(hero);const rng=seeded(201+index);
  for(let i=0;i<7;i++){const a=i/7*Math.PI*2;let tx=Math.sin(a)*4.6,tz=Math.cos(a)*3.8;if(tz>1&&tx>0)continue;const t=theme.trees==='pine'?makePine():makeTree(theme.trees==='cherry'?'cherry':'oak',i+index);t.position.set(tx,.55,tz);t.scale.setScalar(.36+rng()*.13);staticRoot.add(t);}
  const path=mesh(staticRoot,new THREE.CircleGeometry(1,48),mat('#c8b38a'),0,.58,1.6,3.8,1.3,1);path.rotation.x=-Math.PI/2;
  for(const [id,xx,zz,scale]of [['bench',1,3.1,.57],['flowerPatch',-3,1.8,.73],['lantern',-.3,2.7,.78],['flowerPatch',3.1,2.4,.67],['signpost',-1,3.5,.75]]){const o=decor(id);o.position.set(xx,.59,zz);o.scale.setScalar(scale);staticRoot.add(o);}
  if([1,5,7].includes(theme.id)){const lake=cylinder(staticRoot,'#79aaa8',2,.57,1.0,1.05,.055);lake.scale.z=.63;const mini=decor('leaderWaterfall');mini.position.set(3.1,.58,-.2);mini.scale.setScalar(.48);staticRoot.add(mini);}
  batchStatic(staticRoot);batchStatic(base);const placedRoot=new THREE.Group();g.add(placedRoot);islands.push({g,hero,placedRoot,layoutKey:null,targetY:-.65,phase:index*1.5});
  const label=document.createElement('button');label.className='isle-label';label.style.setProperty('--island-color',theme.color);label.innerHTML=`<span>${String(theme.id).padStart(2,'0')}</span><b>${theme.name}</b>`;label.setAttribute('aria-label',`參觀第 ${theme.id} 組 ${theme.name}`);label.onclick=()=>selectIsland(theme.id);$('island-labels').appendChild(label);labels.push(label);
  const vertices=new Float32Array(33*3),geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.BufferAttribute(vertices,3));const line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:'#dddab2',transparent:true,opacity:.38}));scene.add(line);bridges.push(line);syncIsland(index);
}
function makeCenter(){
  const theme={...THEMES[2],id:32,grass:'#9ba985'},g=islandBase(theme,13.8);g.position.y=4.5;scene.add(g);
  const upper=islandBase({...theme,id:42,grass:'#a9b594'},8.7);upper.position.set(0,3.05,-3.1);upper.scale.y=.65;g.add(upper);
  const place=(id,x,y,z,scale,rot=0)=>{const o=decor(id);o.position.set(x,y,z);o.scale.setScalar(scale);o.rotation.y=rot;g.add(o);return o;};
  place('leaderPalace',0,3.45,-4.7,2.35);
  place('gazebo',-9.5,.6,-.2,.8);place('gazebo',9.5,.6,-.2,.8);
  place('leaderStarFountain',0,.65,6.5,1.15);
  place('leaderMoonLake',-7.8,.62,5.6,.9);place('leaderWaterfall',8.8,2.4,2.8,1.3,Math.PI*.18);
  place('leaderWaterfall',-8.8,2.4,2.8,1.3,-Math.PI*.18);
  // Broad terraces and the processional stairs connect the palace to its gardens.
  for(let i=0;i<10;i++)box(g,i%2?'#e0d7b8':'#d5c9a6',0,.65+i*.27,4.3-i*.45,4.6,.3,.72);
  for(const side of [-1,1]){
    for(let i=0;i<5;i++){const x=side*(5.4+i*.75),z=7.3-i*2.4;const tree=makeTree(i%2?'cherry':'oak',420+i);tree.position.set(x,.62,z);tree.scale.setScalar(.42+i*.025);g.add(tree);}
    place('arch',side*5.7,.6,7.2,.74);place('cottage',side*10,.55,-4.9,.63);
    place('telescope',side*5,3.45,-7.8,.58);
    for(let i=0;i<4;i++){place('flowerPatch',side*(2.7+i*.9),.64,8.5,.7);place('lantern',side*3.2,.66,5.5-i*1.8,.58);}
  }
  const tree=makeTree('wish',99);tree.position.set(0,3.45,-9.8);tree.scale.setScalar(1.05);g.add(tree);
  for(let i=0;i<12;i++){const a=i*Math.PI/6;place('starLamp',Math.sin(a)*12.4,.65,Math.cos(a)*10.1,.54);}
  const plaza=cylinder(g,'#d9cba8',0,.58,7.4,4.4,.07);plaza.scale.z=.76;
  batchStatic(g);
}
function makeOcean(){const material=new THREE.ShaderMaterial({uniforms:{time:{value:0},base:{value:new THREE.Color('#79afa9').convertSRGBToLinear()},glint:{value:new THREE.Color('#add0bf').convertSRGBToLinear()}},vertexShader:'varying vec3 p;void main(){p=(modelMatrix*vec4(position,1.)).xyz;gl_Position=projectionMatrix*viewMatrix*vec4(p,1.);}',fragmentShader:'uniform float time;uniform vec3 base;uniform vec3 glint;varying vec3 p;void main(){float wave=sin(p.z*.45+sin(p.x*.065+time*.1)*4.+time*.2);float ripple=smoothstep(.979,1.,wave)*.17;float light=.16+sin(p.x*.025+p.z*.04)*.10+ripple;gl_FragColor=vec4(mix(base,glint,light),1.);\n#include <tonemapping_fragment>\n#include <encodings_fragment>\n}'});ocean=new THREE.Mesh(new THREE.PlaneGeometry(800,800),material);ocean.rotation.x=-Math.PI/2;ocean.position.y=-.5;scene.add(ocean);}
function makeSky(){const rng=seeded(127);for(let i=0;i<18;i++){const g=new THREE.Group();for(let j=0;j<5;j++)ball(g,'#dbe7da',(j-2)*2.6,.3*Math.sin(j),0,3.5,1.0+rng()*.5,1.8);g.position.set((rng()-.5)*220,8+rng()*14,(rng()-.5)*170-20);if(Math.abs(g.position.x)<48&&Math.abs(g.position.z)<39)g.position.z-=70;g.scale.setScalar(.8+rng()*.6);scene.add(g);clouds.push(g);}
  for(let i=0;i<9;i++){const g=new THREE.Group();ball(g,'#e8e7d7',0,0,0,.28,.12,.11);for(const s of [-1,1]){const w=ball(g,'#d1d7ce',0,.03,s*.33,.16,.04,.4);w.rotation.x=s*.15;}g.position.y=15+i;scene.add(g);birds.push(g);}}
function syncIsland(i){const s=states[i],g=growthFor(s.progressScore);const elevation=islandElevation(totalScore(s));islands[i].targetY=elevation.height;bridges[i].visible=elevation.connected;islands[i].g.scale.setScalar(1+g.stage*.026);labels[i].querySelector('b').textContent=s.worldName;labels[i].setAttribute('aria-label',`參觀第 ${i+1} 組 ${s.worldName}`);const island=islands[i],key=JSON.stringify(s.placements);if(key!==island.layoutKey){island.placedRoot.children.forEach(disposeModel);island.placedRoot.clear();const ratio=.063;for(const p of Object.values(s.placements)){const o=decor(p.itemId);o.position.set(p.x*ratio,.62,p.z*ratio);o.scale.setScalar(.21);o.rotation.y=p.rot;island.placedRoot.add(o);}batchStatic(island.placedRoot);island.layoutKey=key;}}
function selectIsland(id){selected=id;const t=THEMES[id-1],s=states[id-1];$('welcome-card').hidden=true;$('island-detail').hidden=false;$('detail-group').textContent=`第 ${String(id).padStart(2,'0')} 組 · ${t.title}`;$('detail-name').textContent=s.worldName;$('detail-description').textContent=t.subtitle;$('detail-image').src=thumbs.item(heroes[id-1]);$('detail-image').alt=t.title+'的主題地標';$('detail-tags').innerHTML=`<span>${t.trees==='cherry'?'花信':t.trees==='pine'?'山林':'綠意'}</span><span>佈置與生活</span><span>唯讀參觀</span>`;$('visit-island').href=islandHref(config,id);labels.forEach((l,i)=>l.classList.toggle('selected',i+1===id));}
function openPanel(title,html){$('panel-title').textContent=title;$('panel-body').innerHTML=html;hydrateIcons($('panel-body'));panel.showModal();}
function rankings(){readStates();openPanel('一起長大的軌跡',`<p class="panel-footnote">每一份努力都有意義。排名總分＝活動加分＋獎勵分數。島嶼逐步升起，1,600 分才亮起與不孤島的連線。</p>${states.map((s,i)=>({s,i})).sort((a,b)=>totalScore(b.s)-totalScore(a.s)||a.i-b.i).map(({s,i},rank)=>`<div class="ranking-row"><span>${String(rank+1).padStart(2,'0')}</span><div><b>${escape(s.worldName)}</b><small>第 ${i+1} 組 · 活動 ${s.score.toLocaleString()} ＋ 獎勵 ${(s.rewardScore||0).toLocaleString()}</small><progress max="1600" value="${Math.min(1600,s.progressScore)}"></progress></div><strong>${totalScore(s).toLocaleString()}</strong></div>`).join('')}<p class="panel-footnote">主領班的星願神境是固定展示，不計分也不列入排行。${config.cloud?'這裡會自動更新本次活動的八組分數。':'這裡只讀取本機測試資料。'}</p>`);}
function wire(){
  window.addEventListener('resize',resize);window.addEventListener('storage',e=>{if(!e.key?.startsWith('emotion-island:local-preview:2027:'))return;readStates();islands.forEach((_,i)=>syncIsland(i));if(selected)selectIsland(selected);});
  window.addEventListener('focus',()=>{readStates();islands.forEach((_,i)=>syncIsland(i));});
  $('rank-button').onclick=rankings;$('close-panel').onclick=()=>panel.close();$('close-detail').onclick=()=>{selected=null;$('island-detail').hidden=true;$('welcome-card').hidden=false;labels.forEach(l=>l.classList.remove('selected'));};
  $('zoom-in').onclick=()=>{camera.zoom=Math.min(2.5,camera.zoom*1.2);camera.updateProjectionMatrix();};$('zoom-out').onclick=()=>{camera.zoom=Math.max(.6,camera.zoom/1.2);camera.updateProjectionMatrix();};$('rotate-view').onclick=()=>{const p=camera.position.clone().sub(controls.target);p.applyAxisAngle(new THREE.Vector3(0,1,0),Math.PI/4);camera.position.copy(controls.target).add(p);controls.update();};$('home-view').onclick=()=>{camera.position.set(66,94,110);controls.target.set(0,4,0);camera.zoom=1;camera.updateProjectionMatrix();controls.update();};
  $('island-list-button').onclick=()=>{openPanel('沿著風，拜訪彼此',`<div class="island-picker">${THEMES.map(t=>`<a href="${islandHref(config,t.id)}" style="--island-color:${t.color}"><span>${String(t.id).padStart(2,'0')}</span><div><b>${escape(states[t.id-1].worldName)}</b><small>${t.subtitle}</small></div>${icon('arrow')}</a>`).join('')}</div><div class="travel-links"><a class="secondary-button" href="${pageHref(config,'emotion_leader_world.html')}">主領班 · 星願神境</a></div>`);};
  $('time-button').onclick=()=>{night=!night;scene.background.set(night?'#3f5a6c':'#91b6b0');scene.fog.color.set(night?'#4b6878':'#aac6ba');sun.intensity=night?.55:1.08;hemi.intensity=night?.59:.79;ocean.material.uniforms.base.value.set(night?'#426e7a':'#79afa9').convertSRGBToLinear();$('time-button').innerHTML=icon(night?'moon':'sun');};
  $('photo-button').onclick=()=>{renderer.render(scene,camera);const url=renderer.domElement.toDataURL('image/png');openPanel('讓這片天空，留下來',`<img class="photo-preview" src="${url}" alt="共感群島的照片"><div class="travel-links"><a class="primary-button" href="${url}" download="共感大世界-${config.room}.png">保存照片</a></div>`);};
  let down;const ray=new THREE.Raycaster();renderer.domElement.addEventListener('pointerdown',e=>down={x:e.clientX,y:e.clientY});renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>6)return;const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=ray.intersectObjects(islands.map(i=>i.g),true);if(hits.length){let o=hits[0].object;while(o&&!o.userData.group)o=o.parent;if(o)selectIsland(o.userData.group);}});
}
function resize(){const w=$('scene').clientWidth,h=$('scene').clientHeight;renderer.setSize(w,h);sceneWidth=w;sceneHeight=h;const aspect=w/h,span=Math.max(94,94/aspect);camera.left=-span*aspect/2;camera.right=span*aspect/2;camera.top=span/2;camera.bottom=-span/2;camera.updateProjectionMatrix();}
function draw(now){requestAnimationFrame(draw);if(document.hidden||(compact&&now-lastDraw<32))return;lastDraw=now;const begin=performance.now();drawCount++;const dt=Math.min(.05,(now-lastTime)/1000);lastTime=now;time+=dt;const reduced=reducedMotion;
  for(let i=0;i<islands.length;i++){const isle=islands[i];isle.g.position.y+=(isle.targetY+(reduced?0:Math.sin(time*.4+isle.phase)*.18)-isle.g.position.y)*Math.min(1,dt*2);animateDecor(isle.hero,reduced?0:time);const p=isle.g.position.clone();p.z+=6.3;p.y+=.1;p.project(camera);labels[i].style.left=`${Math.round((p.x*.5+.5)*sceneWidth)}px`;labels[i].style.top=`${Math.round((-p.y*.5+.5)*sceneHeight)}px`;labels[i].hidden=p.z>1||Math.abs(p.x)>1.04||Math.abs(p.y)>1;const arr=bridges[i].geometry.attributes.position;for(let j=0;j<=32;j++){const f=j/32;arr.setXYZ(j,isle.g.position.x*f,6+(isle.g.position.y-6)*f-Math.sin(f*Math.PI)*1.8,isle.g.position.z*f);}arr.needsUpdate=true;bridges[i].geometry.computeBoundingSphere();}
  if(!reduced){ocean.material.uniforms.time.value=time;clouds.forEach(c=>{c.position.x+=dt*.075;if(c.position.x>140)c.position.x=-140;});birds.forEach((b,i)=>{const a=time*.05+i*.71;b.position.set(Math.sin(a)*(22+i*2),16+i*.7+Math.sin(time*.5+i)*.5,Math.cos(a)*(18+i));b.rotation.y=-a+Math.PI/2;for(let j=1;j<b.children.length;j++)b.children[j].rotation.x=Math.sin(time*3+i)*(j%2?1:-1)*.28;});}
  controls.update();renderer.shadowMap.needsUpdate=drawCount%3===1;renderer.render(scene,camera);renderMean=renderMean*.97+(performance.now()-begin)*.03;if(drawCount>180&&drawCount%180===0&&renderMean>(compact?26:23)&&renderer.getPixelRatio()>(compact?.85:1))renderer.setPixelRatio(Math.max(compact?.85:1,renderer.getPixelRatio()*.85));
}
